config/routes.rb
Rails.application.routes.draw do
  resources :people
  get '/people/:id/proceed', to: 'people#proceed', as: 'proceed'
  root to: 'people#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_many :people
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :states
  has_many :people
end

app/models/person.rb
class Person < ApplicationRecord
   #validates :email, format: { with: /@/ }, uniqueness: { case_sensitive: false }

   validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

   belongs_to :country
   belongs_to :state
  # belongs_to :city
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  has_many :cities
  has_many :people
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :show_flash

  private

  def show_flash
    flash.now[:notice] = "Found the about page!" if request.path == '/pages/about'
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @person = Person.all
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    # render :json => @person
    if @person.email == @person.email_confirm
      #render :json => @person
      if @person.save
        flash.now[:notice] = "Successfully Created and Waiting for Next Action"
        redirect_to :action => 'show', :id => @person.id
      else
        flash.now[:danger] = "Something Went Wrong"
        render :action => 'new'
      end
    else
      flash.now[:danger] = "Email not matched"
      render :action => :new
    end
  end


  def person_params
    params.require(:person).permit(:first_name, :last_name, :email, :country_id, :state_id, :email_confirm)
  end


  def show
    @person = Person.find(params[:id])
  end


  def edit
    @person = Person.find(params[:id])
  end



  def update
    @person = Person.find(params[:id])
    if person_params['email'] == person_params['email_confirm']
      if @person.update_attributes(person_params)
        flash.now[:notice] = "Successfully Updated"
        redirect_to :action => 'show', :id => @person.id
      else
        flash.now[:danger] = "Something Went Wrong"
        render :action => :edit
      end
    else
      flash.now[:danger] = "Email not matched"
      render :action => :edit
    end
  end


  def destroy
    if Person.destroy(params[:id])
      flash.now[:notice] = "Successfully Deleted"
      render :action =>  :index
    end
  end


  def proceed
    @person = Person.find(params[:id])
     if UserMailer.welcome_email(@person).deliver_later
       flash.now[:notice] = "Congrats, Mail sent successfully!!"
       render 'message'
     else
       flash.now[:danger] = "Something Went Wrong!"
       render 'message'
     end
  end




end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-dark bg-inverse">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "Rails bootstrap", root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Bootstrap" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>

<div class="jumbotron">
  <h1 class="display-4">About the Website</h1>
  <p class="lead">
    This web application was created with
    <%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
    from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
  </p>
</div>

app/views/people/edit.html.erb
<div class="jumbotron">
  <div class="card">
    <div class="card-header">
      <h2 class="text-center"> Edit Details </h2>
    </div>
  </div>
  <p class="lead">
    <%= simple_form_for @person,  :html => {class: 'subscribe-from'}  do |form| %>
    <div class="form-group">
      <label for="formGroupExampleInput">First Name</label>
      <%= form.text_field :first_name , class: "form-control", placeholder: "First Name"%>
    </div>
    <div class="form-group">
      <label for="formGroupExampleInput2">Last Name</label>
      <%= form.text_field :last_name , class: "form-control", placeholder: "Last Name"%>
    </div>
    <div class="form-group">
      <label for="formGroupExampleInput3">Email</label>
      <%= form.email_field :email , class: "form-control", placeholder: "Email"%>
    </div>
    <div class="form-group">
      <label for="formGroupExampleInput3">Confirm Email</label>
      <%= form.email_field :email_confirm , class: "form-control", placeholder: "Confirm Email"%>
    </div>
    <div class="form-group">
      <label for="formGroupExampleInput5">Country</label>
      <%= form.collection_select :country_id, Country.order(:name), :id, :name, include_blank: true  %>
    </div>
    <div class="form-group">
      <label for="formGroupExampleInput6">City</label>
      <%= form.grouped_collection_select :state_id, Country.order(:name), :states, :name, :id, :name, include_blank: true %>
    </div>
    <div class="col-md-12 col-md-offset-3">
      <%= form.submit "Update Information", class: "btn btn-success btn-block" %>
    </div>
  <%end%>


  </p>
</div>

<style>
  select#person_country_id {
    height: 34px;
    width: 100%; !important;
  }
  select#person_state_id {
    height: 34px;
    width: 100%; !important;
  }
</style>

app/views/people/index.html.erb
<div class="jumbotron">
  <div class="card">
    <div class="card-header">
      <h2 class="text-center"> Mail Sending List </h2>
    </div>
  </div>
  <p class="lead">


  <table class="table table-bordered">
      <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Country</th>
        <th>City</th>
        <th>Option</th>
      </tr>
      </thead>

      <% @person.each do |person| %>
        <tr>
          <td><%=  person.first_name %></td>
          <td><%=  person.last_name %></td>
          <td><%=  person.email %></td>
          <td><%=  person.country.name %></td>
          <td><%=  person.state.name %></td>
          <td>
            <%= link_to 'Show', person_path(person.id) %>
          </td>
        </tr>
      <% end -%>
    </table>

    <br>
    <p><%= link_to 'New', new_person_path,  class: "btn btn-success"%></p>

  </p>
</div>

app/views/people/message.html.erb
<div class="jumbotron">
  <div class="card">
    <div class="card-header">
      <h2 class="text-center"> Message </h2>
    </div>
  </div>
  <p class="lead text-center"><br>
    <%= notice %>
  </p>
</div>

app/views/people/new.html.erb
<div class="jumbotron">
  <div class="card">
    <div class="card-header">
     <h2 class="text-center"> Welcome to Rails </h2>
    </div>
  </div>
  <p class="lead">

      <%= simple_form_for @person, :html => {class: 'subscribe-from'}  do |form| %>
        <div class="form-group">
            <label for="formGroupExampleInput">First Name</label>
            <%= form.text_field :first_name , class: "form-control",  placeholder: "First Name" %>
          </div>
          <div class="form-group">
            <label for="formGroupExampleInput2">Last Name</label>
            <%= form.text_field :last_name , class: "form-control", placeholder: "Last Name" %>
          </div>
          <div class="form-group">
            <label for="formGroupExampleInput3">Email</label>
            <%= form.email_field :email , class: "form-control", placeholder: "Email"%>
          </div>
          <div class="form-group">
            <label for="formGroupExampleInput3">Confirm Email</label>
            <%= form.email_field :email_confirm , class: "form-control", placeholder: "Confirm Email"%>
          </div>

          <div class="form-group row">
            <div class="col">
              <label for="formGroupExampleInput4">Country</label><br>
              <%= form.collection_select :country_id, Country.order(:name), :id, :name, class: "form-control",class: "custom-select mr-sm-2", include_blank: true  %>
            </div>
            <div class="col">
              <label for="formGroupExampleInput5">City</label><br>
              <%= form.grouped_collection_select :state_id, Country.order(:name), :states, :name, :id, :name, class: "form-control", include_blank: true %>
            </div>
          </div>


          <div class="col-md-12 col-md-offset-3">
            <%= form.submit "Submit", class: "btn btn-success btn-block" %>
        </div>
      <%end%>
  </p>
</div>


<style>
  select#person_country_id {
    height: 34px;
    width: 100%; !important;
  }
  select#person_state_id {
    height: 34px;
    width: 100%; !important;
  }
</style>

app/views/people/show.html.erb
<div class="jumbotron">
  <div class="card">
    <div class="card-header">
      <h2 class="text-center"> Preview Information </h2>
    </div>
  </div>
  <p class="lead">
    <div class="text-center">
      <h2>First Name: <%= @person.first_name %></h2>
      <h2>Last Name: <%= @person.last_name %></h2>
      <h2>Email: <%= @person.email %></h2>
      <h2>Country: <%= @person.country.name %></h2>
      <h2>City: <%= @person.state.name %></h2>
      <a  href="/people/<%= @person.id %>/edit", class="btn btn-info">Edit</a>
      <a  href="/people/<%= @person.id %>/proceed", class="btn btn-info">Proceed</a>
    </div>
  </p>
</div>

app/views/visitors/index.html.erb
<div class="jumbotron">
  <h3 class="display-3 text-center"><b>Welcome to Rails</b></h3>
  <p class="lead">
    <form action="/">
      <div class="form-group">
        <label for="formGroupExampleInput">First Name</label>
        <input type="text" class="form-control" id="formGroupExampleInput" placeholder="First Name">
      </div>
      <div class="form-group">
        <label for="formGroupExampleInput2">Last Name</label>
        <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Last Name...">
      </div>
      <div class="form-group">
        <label for="formGroupExampleInput3">Email</label>
        <input type="text" class="form-control" id="formGroupExampleInput3" placeholder="Email...">
      </div>
      <div class="form-group">
        <label for="formGroupExampleInput4">Confirm Email</label>
        <input type="text" class="form-control" id="formGroupExampleInput4" placeholder="Email Confirm...">
      </div>
      <div class="form-group">
        <label for="formGroupExampleInput5">Country</label>
        <input type="text" class="form-control" id="formGroupExampleInput5" placeholder="Another input">
      </div>
      <div class="form-group">
        <label for="formGroupExampleInput6">City</label>
        <input type="text" class="form-control" id="formGroupExampleInput6" placeholder="Another input">
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>


  </p>
</div>